## NLP Final
### Part 3: Named Entity Recognition - Analysis
### Aren Mizuno
### March 12, 2026

In [2]:
# Imports
import pandas as pd
from google.colab import drive

In [3]:
# Mount drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
# Load data ner
ner_path = "/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/parquets/ner.parquet"
ner = pd.read_parquet(ner_path, engine="pyarrow")
ner.head(2)

,url,date,title,text,text_for_extraction,text_clean,company,technology
0,https://blockworks.co/price/bad,2025-06-23,"Bad Idea AI Price (BAD), Market Cap, Price Tod...","Bad Idea AI Price (BAD), Market Cap, Price Tod...","Bad Idea AI Price (BAD), Market Cap, Price Tod...","bad idea ai price (bad), market cap, price tod...",[Bad Idea AI Price],[]
1,https://boingboing.net/2024/07/01/this-ai-vide...,2024-07-01,This AI video of gymnastics might be the freak...,This AI video of gymnastics might be the freak...,This AI video of gymnastics might be the freak...,this ai video of gymnastics might be the freak...,"[Instagram, Trump, Werners AI Art]",[]

In [5]:
# Load data bertopic text
bertopic_text_path = "/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/parquets/bertopic_text.parquet"
bertopic_text = pd.read_parquet(bertopic_text_path, engine="pyarrow")
bertopic_text.head(2)

,url,date,title,text,bertopic_topic_text
0,https://blockworks.co/price/bad,2025-06-23,"Bad Idea AI Price (BAD), Market Cap, Price Tod...",bad idea ai price bad market cap price today c...,10
1,https://boingboing.net/2024/07/01/this-ai-vide...,2024-07-01,This AI video of gymnastics might be the freak...,this ai video of gymnastics might be the freak...,0

In [6]:
# Companies
companies_exploded = ner["company"].explode().dropna()

company_counts = companies_exploded.value_counts()

print("Top Companies:")
print(company_counts.head(20))

print("\nTotal unique companies:", company_counts.shape[0])
print("Total company mentions:", companies_exploded.shape[0])

Top Companies:
company
Google                     21352
Microsoft                  15467
Amazon                     10361
Apple                       8024
Instagram                   6570
Meta                        6280
Nvidia                      5139
Facebook                    4954
Nexstar Media Inc           2760
Tesla                       2530
Samsung                     2511
Intel                       2334
Artificial Intelligence     2249
Generative AI               2224
Cision US Inc               2196
Newsmatics Inc              2175
Gray Media Group            2151
Gray Television, Inc        2118
Research                    2101
IBM                         2088
Name: count, dtype: int64

Total unique companies: 71885
Total company mentions: 357926

In [7]:
# Technologies
tech_exploded = ner["technology"].explode().dropna()

tech_counts = tech_exploded.value_counts()

print("\nTop Technologies:")
print(tech_counts.head(20))

print("\nTotal unique technologies:", tech_counts.shape[0])
print("Total technology mentions:", tech_exploded.shape[0])

Top Technologies:
technology
artificial intelligence           84072
generative ai                     33503
chatbot                           27612
ai model                          24618
large language model              20954
machine learning                  19631
robotics                           6864
deep learning                      4369
natural language processing        4268
computer vision                    3314
neural network                     3149
foundation model                   2212
fine-tuning                        1522
transformer                        1436
reinforcement learning             1118
retrieval-augmented generation     1062
autonomous driving                  965
prompt engineering                  923
multimodal ai                       515
embeddings                          284
Name: count, dtype: int64

Total unique technologies: 25
Total technology mentions: 243387

In [8]:
# Topic → label mapping
topic_map = {
    -1: "Cross-Industry AI News / Outliers",
    0: "Enterprise Technology",
    1: "Consumer & Public Services",
    2: "Financial Services & Business",
    3: "Corporate AI Announcements",
    4: "Enterprise Software & Cybersecurity",
    5: "Healthcare & Life Sciences",
    6: "Financial Markets & Investing",
    7: "Media, Journalism & Public Policy",
    8: "Business Operations & Enterprise Automation",
    9: "Workforce & Compensation",
    10: "Cryptocurrency & Digital Assets",
    11: "Publishing & Intellectual Property",
    12: "Public AI Companies",
    13: "Technology Industry News",
    14: "Music & Entertainment",
    15: "African Technology Development",
    16: "AI Market Commentary"
}

# Replace topic numbers with labels
bertopic_text["topic_label"] = bertopic_text["bertopic_topic_text"].map(topic_map)

In [9]:
# Merge dfs
merged = bertopic_text[["url", "topic_label"]].merge(
    ner[["url", "company", "technology"]],
    on="url",
    how="inner"
)

print("Merged shape:", merged.shape)
display(merged.head(2))

Merged shape: (136233, 4)

,url,topic_label,company,technology
0,https://blockworks.co/price/bad,Cryptocurrency & Digital Assets,[Bad Idea AI Price],[]
1,https://boingboing.net/2024/07/01/this-ai-vide...,Enterprise Technology,"[Instagram, Trump, Werners AI Art]",[]

In [10]:
# Top 10 companies and technology by topic
for topic in sorted(merged["topic_label"].dropna().unique()):
    print("\n" + "="*60)
    print(f"TOPIC {topic}")
    print("="*60)

    top_comp = (
        merged.loc[merged["topic_label"] == topic, "company"]
        .explode()
        .dropna()
        .value_counts()
        .head(10)
    )

    top_tech = (
        merged.loc[merged["topic_label"] == topic, "technology"]
        .explode()
        .dropna()
        .value_counts()
        .head(10)
    )

    print("\nTop Companies:")
    print(top_comp)

    print("\nTop Technologies:")
    print(top_tech)

============================================================
TOPIC AI Market Commentary
============================================================

Top Companies:
company
My European Quotes    446
Motley                269
Nvidia                261
Amazon                170
Microsoft             134
Alphabet              122
TradeTalks            116
AMD                    63
Nasdaq, Inc            61
Google                 60
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence    664
generative ai              187
ai model                   168
large language model       123
machine learning            88
chatbot                     63
robotics                    58
autonomous driving          21
foundation model            15
computer vision             12
Name: count, dtype: int64

============================================================
TOPIC African Technology Development
============================================================

Top Companies:
company
Google                     176
Arena Holdings             114
Microsoft                   98
Facebook                    62
Apple                       52
Twitter                     43
Meta                        41
Instagram                   40
Amazon                      39
Artificial Intelligence     38
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence        782
machine learning               228
generative ai                  175
chatbot                        168
ai model                       154
large language model           108
robotics                        68
natural language processing     31
deep learning                   31
computer vision                 23
Name: count, dtype: int64

============================================================
TOPIC Business Operations & Enterprise Automation
============================================================

Top Companies:
company
Gray Media Group           1436
Gray Television, Inc       1385
Gray Media Group, Inc       335
PRNewswire                  316
Google                       83
Generative AI                74
Amazon                       55
Artificial Intelligence      48
Microsoft                    46
Instagram                    39
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence        944
machine learning               543
generative ai                  511
large language model           304
ai model                       228
deep learning                  143
computer vision                130
natural language processing    130
chatbot                        119
robotics                        70
Name: count, dtype: int64

============================================================
TOPIC Consumer & Public Services
============================================================

Top Companies:
company
Nexstar Media Inc    1863
Google               1564
Microsoft            1083
BestReviews           795
Amazon                765
Facebook              471
Meta                  399
Apple                 365
Instagram             289
Android               210
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence        5109
chatbot                        2214
generative ai                  1626
large language model           1041
ai model                        910
machine learning                480
foundation model                179
robotics                        150
computer vision                  76
natural language processing      70
Name: count, dtype: int64

============================================================
TOPIC Corporate AI Announcements
============================================================

Top Companies:
company
Newsmatics Inc           2102
Industry Newswires       1142
EIN Presswire             446
Google                    205
New Mexico                203
Microsoft                 122
TBRC Research Pvt Ltd     114
Allied Analytics LLP      114
IBM                       103
Generative AI              98
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence        1833
machine learning                869
generative ai                   719
ai model                        414
large language model            386
natural language processing     331
chatbot                         283
deep learning                   261
computer vision                 216
robotics                        214
Name: count, dtype: int64

============================================================
TOPIC Cross-Industry AI News / Outliers
============================================================

Top Companies:
company
Google               5095
Microsoft            3919
Amazon               2681
Instagram            2123
Apple                2119
Facebook             1744
Meta                 1573
Nvidia               1309
Digital               897
Nexstar Media Inc     777
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence        21921
generative ai                   8569
chatbot                         7099
ai model                        5933
large language model            5104
machine learning                4924
robotics                        1605
deep learning                   1032
natural language processing     1005
computer vision                  850
Name: count, dtype: int64

============================================================
TOPIC Cryptocurrency & Digital Assets
============================================================

Top Companies:
company
Ethereum                 214
Bollinger Bands          210
Google                   195
Bitcoin                   75
AITECH                    60
Account                   56
DepositStep               44
Link Machine Learning     37
MEXC Spot                 33
Daily Email               27
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence        145
machine learning               117
deep learning                   45
large language model            29
ai model                        21
chatbot                         12
robotics                         8
neural network                   5
natural language processing      5
generative ai                    2
Name: count, dtype: int64

============================================================
TOPIC Enterprise Software & Cybersecurity
============================================================

Top Companies:
company
Cision US Inc                    2062
PR Newswire                       631
Release Resources Journalists     364
CNW Group Ltd                     289
Client Send                       192
Call PR Newswire                  192
Register Now                      183
Microsoft                         111
Google                            111
Generative AI                     110
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence        3093
generative ai                   883
machine learning                666
large language model            520
ai model                        494
robotics                        226
chatbot                         204
deep learning                   157
natural language processing     156
computer vision                 130
Name: count, dtype: int64

============================================================
TOPIC Enterprise Technology
============================================================

Top Companies:
company
Google       10187
Microsoft     7951
Amazon        4973
Apple         4303
Meta          3283
Instagram     3090
Nvidia        2572
Facebook      2039
Samsung       1764
Research      1630
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence        36996
generative ai                  16727
chatbot                        13891
ai model                       13060
large language model           10877
machine learning                9112
robotics                        3607
deep learning                   2151
natural language processing     2143
neural network                  1619
Name: count, dtype: int64

============================================================
TOPIC Financial Markets & Investing
============================================================

Top Companies:
company
Nasdaq, Inc. All              631
Microsoft                     511
Amazon                        452
Google                        434
Nvidia                        404
Indian Railway Corporation    337
Apple                         288
Alphabet                      249
Watchlist                     183
TSLA AAPL                     147
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence        2051
generative ai                  1112
chatbot                         645
ai model                        602
large language model            587
machine learning                400
robotics                        126
natural language processing      61
deep learning                    60
computer vision                  58
Name: count, dtype: int64

============================================================
TOPIC Financial Services & Business
============================================================

Top Companies:
company
Google                  784
Microsoft               633
Standard Private Ltd    445
Amazon                  428
Apple                   342
Instagram               315
Meta                    288
ChartsForex             280
Nvidia                  246
Technologies            151
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence        3073
chatbot                        1153
generative ai                  1123
ai model                        926
large language model            777
machine learning                573
robotics                        204
deep learning                   120
natural language processing     107
neural network                   98
Name: count, dtype: int64

============================================================
TOPIC Healthcare & Life Sciences
============================================================

Top Companies:
company
Google                     223
Research                   140
Microsoft                  125
Healthcare                 122
Amazon                     104
Facebook                   103
Instagram                   80
Artificial Intelligence     80
Market Data                 79
Apple                       76
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence        2226
machine learning                872
ai model                        597
generative ai                   443
chatbot                         366
large language model            353
deep learning                   272
robotics                        205
neural network                  137
natural language processing     131
Name: count, dtype: int64

============================================================
TOPIC Media, Journalism & Public Policy
============================================================

Top Companies:
company
Google                      360
Microsoft                   296
Meta                        204
Community Advisory Board    178
Facebook                    165
Amazon                      150
Instagram                   148
Apple                       105
Digital TV Channels         102
Trump                        98
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence        2151
chatbot                         708
generative ai                   463
ai model                        416
large language model            313
machine learning                152
robotics                         60
neural network                   45
reinforcement learning           19
natural language processing      13
Name: count, dtype: int64

============================================================
TOPIC Music & Entertainment
============================================================

Top Companies:
company
Google                   116
Instagram                100
Apple                     67
Universal Music Group     63
Facebook                  62
Spotify                   61
Amazon                    56
Microsoft                 48
Meta                      33
Twitter                   31
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence        605
generative ai                  216
ai model                       168
chatbot                        122
machine learning                69
large language model            42
robotics                        19
neural network                  18
natural language processing     10
deep learning                    7
Name: count, dtype: int64

============================================================
TOPIC Public AI Companies
============================================================

Top Companies:
company
Google                      161
NASDAQ                       54
Palladyne AI Corp            39
SES AI Corporation           37
SoundHound AI Inc            33
Airship AI Holdings, Inc     31
MarketBeat                   28
Pony AI Inc                  22
LLC Sells                    22
Bullfrog AI Holdings Inc     21
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence    549
robotics                   163
machine learning           142
generative ai               17
supervised learning          5
computer vision              5
unsupervised learning        5
autonomous driving           5
large language model         4
ai model                     4
Name: count, dtype: int64

============================================================
TOPIC Publishing & Intellectual Property
============================================================

Top Companies:
company
Google                        303
Cox Media Group               269
Cox Media Group Television    263
Microsoft                     210
Amazon                        152
Facebook                       88
Meta                           75
Instagram                      75
Cox Media Group(Opens          72
Apple                          64
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence    1006
chatbot                     390
generative ai               345
ai model                    196
large language model        151
machine learning             58
foundation model             35
computer vision              18
robotics                     17
neural network               12
Name: count, dtype: int64

============================================================
TOPIC Technology Industry News
============================================================

Top Companies:
company
Google                322
Microsoft             172
Amazon                133
Meta                   87
Nvidia                 78
Apple                  72
Instagram              29
AMD                    28
Intel                  27
Meta Platforms Inc     27
Name: count, dtype: int64

Top Technologies:
technology
artificial intelligence        922
generative ai                  384
ai model                       326
machine learning               309
large language model           214
chatbot                        171
robotics                        61
natural language processing     58
multimodal ai                   38
neural network                  34
Name: count, dtype: int64

============================================================
TOPIC Workforce & Compensation
============================================================

Top Companies:
company
Google                           973
Location                         822
Data Scientist                   630
Levels Fyi Inc.ChangeDownload    300
Levels.fyi                       276
FAANG                            150
ExperienceTotal                   97
Heatmap                           82
LinkedIn                          52
Data Science                      30
Name: count, dtype: int64

Top Technologies:
technology
machine learning           29
large language model       21
robotics                    3
artificial intelligence     2
generative ai               1
ai model                    1
computer vision             1
supervised learning         1
reinforcement learning      1
Name: count, dtype: int64